services:

  externalsys-srv:
    container_name: externalsys-srv
    image: hong3206/externalsys-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    ports:
      - "9091:9091"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  menumanagement-srv:
    container_name: menumanagement-srv
    image: hong3206/menumanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.redis.host=redis
    ports:
      - "9098:9098"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  adminmanagement-srv:
    container_name: adminmanagement-srv
    image: hong3206/adminmanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.datasource.url=jdbc:h2:tcp://h2:1521/macdrop
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "9096:9096"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  notificationmanagement-srv:
    container_name: notificationmanagement-srv
    image: hong3206/notificationmanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "9097:9097"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  ordermanagement-srv:
    container_name: ordermanagement-srv
    image: hong3206/ordermanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.datasource.url=jdbc:h2:tcp://h2:1521/macdrop
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "9095:9095"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  accountingbilling-srv:
    container_name: accountingbilling-srv
    image: hong3206/accountingbilling-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.datasource.url=jdbc:h2:tcp://h2:1521/macdrop
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "9094:9094"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv
      - cartmanagement-srv

  cartmanagement-srv:
    container_name: cartmanagement-srv
    image: hong3206/cartmanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.redis.host=redis
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "9093:9093"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq
      - usermanagement-srv

  usermanagement-srv:
    container_name: usermanagement-srv
    image: hong3206/usermanagement-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.datasource.url=jdbc:h2:tcp://h2:1521/macdrop
    ports:
      - "9092:9092"
    depends_on:
      - eureka
      - h2
      - redis
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq-infra
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis-infra
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"

  h2:
    container_name: h2-infra
    image: oscarfonts/h2
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - "1521:1521"
      - "81:81"

  eureka:
    container_name: eureka-infra
    image: hong3206/eureka-infra
    environment:
      - eureka.instance.ipAddress="127.0.0.1"
    ports:
      - "8761:8761"