INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm0', '******', 'f0', 'l0', 1000, 'u0@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm1', '******', 'f1', 'l1', 1000, 'u1@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm2', '******', 'f2', 'l2', 1000, 'u2@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm3', '******', 'f3', 'l3', 1000, 'u3@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm4', '******', 'f4', 'l4', 1000, 'u4@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm5', '******', 'f5', 'l5', 1000, 'u5@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm6', '******', 'f6', 'l6', 1000, 'u6@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm7', '******', 'f7', 'l7', 1000, 'u7@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm8', '******', 'f8', 'l8', 1000, 'u8@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm9', '******', 'f9', 'l9', 1000, 'u9@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm10', '******', 'f10', 'l10', 1000, 'u10@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm11', '******', 'f11', 'l11', 1000, 'u11@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm12', '******', 'f12', 'l12', 1000, 'u12@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm13', '******', 'f13', 'l13', 1000, 'u13@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm14', '******', 'f14', 'l14', 1000, 'u14@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm15', '******', 'f15', 'l15', 1000, 'u15@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm16', '******', 'f16', 'l16', 1000, 'u16@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm17', '******', 'f17', 'l17', 1000, 'u17@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm18', '******', 'f18', 'l18', 1000, 'u18@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm19', '******', 'f19', 'l19', 1000, 'u19@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm20', '******', 'f20', 'l20', 1000, 'u20@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm21', '******', 'f21', 'l21', 1000, 'u21@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm22', '******', 'f22', 'l22', 1000, 'u22@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm23', '******', 'f23', 'l23', 1000, 'u23@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm24', '******', 'f24', 'l24', 1000, 'u24@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm25', '******', 'f25', 'l25', 1000, 'u25@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm26', '******', 'f26', 'l26', 1000, 'u26@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm27', '******', 'f27', 'l27', 1000, 'u27@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm28', '******', 'f28', 'l28', 1000, 'u28@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm29', '******', 'f29', 'l24', 1000, 'u29@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm30', '******', 'f30', 'l30', 1000, 'u30@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm31', '******', 'f31', 'l31', 1000, 'u31@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm32', '******', 'f32', 'l32', 1000, 'u32@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm33', '******', 'f33', 'l33', 1000, 'u33@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm34', '******', 'f34', 'l34', 1000, 'u34@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm35', '******', 'f35', 'l35', 1000, 'u35@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm36', '******', 'f36', 'l36', 1000, 'u36@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm37', '******', 'f37', 'l37', 1000, 'u37@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm38', '******', 'f38', 'l38', 1000, 'u38@mcmaster.ca');
INSERT INTO COMMUNITYMEMBER (Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('cm39', '******', 'f39', 'l39', 1000, 'u39@mcmaster.ca');

INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker0', '******', 'f0', 'l0', 0, 0, 'biker0@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker1', '******', 'f1', 'l1', 0, 0, 'biker1@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker2', '******', 'f2', 'l2', 0, 0, 'biker2@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker3', '******', 'f3', 'l3', 0, 0, 'biker3@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker4', '******', 'f4', 'l4', 0, 0, 'biker4@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker5', '******', 'f5', 'l5', 0, 0, 'biker5@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker6', '******', 'f6', 'l6', 0, 0, 'biker6@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker7', '******', 'f7', 'l7', 0, 0, 'biker7@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker8', '******', 'f8', 'l8', 0, 0, 'biker8@mcmaster.ca');
INSERT INTO BIKER(Username, Password, FirstName, LastName, CurrentWorkload, HistoryWorkload, ETFemail) VALUES ('biker9', '******', 'f9', 'l9', 0, 0, 'biker9@mcmaster.ca');

INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp0', '******', 'f0', 'l0', 'fp0@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp1', '******', 'f1', 'l1', 'fp1@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp2', '******', 'f2', 'l2', 'fp2@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp3', '******', 'f3', 'l3', 'fp3@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp4', '******', 'f4', 'l4', 'fp4@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp5', '******', 'f5', 'l5', 'fp5@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp6', '******', 'f6', 'l6', 'fp6@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp7', '******', 'f7', 'l7', 'fp7@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp8', '******', 'f8', 'l8', 'fp8@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp9', '******', 'f9', 'l9', 'fp9@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp10', '******', 'f10', 'l10', 'fp10@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp11', '******', 'f11', 'l11', 'fp11@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp12', '******', 'f12', 'l12', 'fp12@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp13', '******', 'f13', 'l13', 'fp13@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp14', '******', 'f14', 'l14', 'fp14@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp15', '******', 'f15', 'l15', 'fp15@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp16', '******', 'f16', 'l16', 'fp16@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp17', '******', 'f17', 'l17', 'fp17@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp18', '******', 'f18', 'l18', 'fp18@mcmaster.ca');
INSERT INTO FOODPROVIDER(Username, Password, FirstName, LastName, ETFemail) VALUES ('fp19', '******', 'f19', 'l19', 'fp19@mcmaster.ca');

INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso0', '******', 'f0', 'l0', 200, 'bso0@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso1', '******', 'f1', 'l1', 200, 'bso1@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso2', '******', 'f2', 'l2', 200, 'bso2@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso3', '******', 'f3', 'l3', 200, 'bso3@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso4', '******', 'f4', 'l4', 200, 'bso4@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso5', '******', 'f5', 'l5', 200, 'bso5@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso6', '******', 'f6', 'l6', 200, 'bso6@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso7', '******', 'f7', 'l7', 200, 'bso7@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso8', '******', 'f8', 'l8', 200, 'bso8@mcmaster.ca');
INSERT INTO BOOKSTOREOPERATOR(Username, Password, FirstName, LastName, CurrentMdd, ETFemail) VALUES ('bso9', '******', 'f9', 'l9', 200, 'bso9@mcmaster.ca');

INSERT INTO ADMIN(Username, Password, FirstName, LastName, ETFemail) VALUES ('admin0', '******', 'f0', 'l0', 'admin0@mcmaster.ca');
INSERT INTO ADMIN(Username, Password, FirstName, LastName, ETFemail) VALUES ('admin1', '******', 'f1', 'l1', 'admin1@mcmaster.ca');
INSERT INTO ADMIN(Username, Password, FirstName, LastName, ETFemail) VALUES ('admin2', '******', 'f2', 'l2', 'admin2@mcmaster.ca');
INSERT INTO ADMIN(Username, Password, FirstName, LastName, ETFemail) VALUES ('admin3', '******', 'f3', 'l3', 'admin3@mcmaster.ca');
INSERT INTO ADMIN(Username, Password, FirstName, LastName, ETFemail) VALUES ('admin4', '******', 'f4', 'l4', 'admin4@mcmaster.ca');

INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location0', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location1', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location2', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location3', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location4', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location5', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location6', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location7', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location8', 0, 0);
INSERT INTO LOCATION(Name, CurrentWorkload, HistoryWorkload) VALUES ('location9', 0, 0);

INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000003', '20000005', 'food1(ID20000005001); food2(ID20000005002);', '90.00', '2022-10-30 10:30:54', NULL, NULL, NULL,  'location & time needed');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000004', '20000005', 'food1(ID20000005001); food2(ID20000005002);', '120.00', '2022-10-30 10:46:54', '30000002', '80000001', '2022-10-30 14:55:54',  'dropped-off & complete');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000005', '20000005', 'food1(ID20000005001); food2(ID20000005002);', '100.00', '2022-10-30 10:59:54', '30000002', '80000002', '2022-10-30 14:59:54',  'dropped-off & complete');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000005', '20000006', 'food1(ID20000006001); food2(ID20000006002);', '120.00', '2022-10-30 11:59:54', '30000002', '80000002', '2022-10-30 16:59:54',  'dropped-off & complete');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000005', '20000007', 'food1(ID20000007001); food2(ID20000007002);', '110.00', '2022-10-30 12:59:54', '30000002', '80000002', '2022-10-30 13:59:54',  'dropped-off & complete');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000006', '20000008', 'food1(ID20000008001); food2(ID20000008002);', '110.00', '2022-10-19 13:01:54', '30000002', '80000002', '2022-10-19 14:01:54',  'dropped-off & complete');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000008', '20000002', 'food1(ID20000002001); food2(ID20000002002);', '40.00', '2022-10-11 13:01:54', '30000001', '80000001', '2022-10-11 14:01:54',  'accepted & waiting for pickup');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000008', '20000003', 'food1(ID20000003001); food2(ID20000003002);', '50.00', '2022-10-11 13:01:54', '30000001', '80000001', '2022-10-11 14:01:54',  'accepted & waiting for pickup');
INSERT INTO FOODORDER(CommunityMemberID, FoodProviderID, FoodItems, FoodOrderPrice, OrderTime, BikerID, DropOffLocationID, EstimatedPickupTime, Status) VALUES ('10000008', '20000004', 'food1(ID20000004001); food2(ID20000004002);', '60.00', '2022-10-11 13:01:54', '30000001', '80000001', '2022-10-11 14:01:54',  'accepted & waiting for pickup');

INSERT INTO BOOKSTOREORDER(CommunityMemberID, BookstoreOperatorID , BookStoreItems , MDDPrice , OrderTime) VALUES ('10000006', '40000001', 'Java textbook1(ID:40000001001);', '20', '2022-10-19 10:44:52');
INSERT INTO BOOKSTOREORDER(CommunityMemberID, BookstoreOperatorID , BookStoreItems , MDDPrice , OrderTime) VALUES ('10000006', '40000001', 'Java textbook2(ID:40000001002);', '10', '2022-10-20 10:44:52');